---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: ../../roles
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 8000, host: 8894}]
  - name: centos-7.1
    driver_config:
      network:
        - ["forwarded_port", {guest: 8000, host: 8897}]

suites:
  - name: default
    run_list:
    attributes:

