---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  name: chef_solo

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 8000, host: 8894}]
  - name: centos-7.1
    driver_config:
      network:
        - ["forwarded_port", {guest: 8000, host: 8897}]

suites:
  - name: default
    run_list:
    attributes:
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
      - centos-7.1
  - name: default-postgres
    run_list:
    attributes:
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
      - centos-7.1
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default/centos.yml
  - name: default-v1
    run_list:
    attributes:
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
      - centos-7.1
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default-v1/default.yml
  - name: default-v1-postgres
    run_list:
    attributes:
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
#      - centos-7.1
#      - centos-6
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default-v1-postgres/default.yml


