---
## https://github.com/Netflix/Scumblr/wiki

- name: apt | scumblr packages dependencies
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - libxml2-dev
    - build-essential
    - bison
    - openssl
    - zlib1g
    - libxslt1.1
    - libssl-dev
#    - libxslt-dev      ## Note: it's an alias and requesting it, alter apt output in a way ansible believes task is always in changed state. BUG/FIXME!
    - libxslt1.1
    - libxslt1-dev
    - libxml2
    - libffi-dev
    - libpq-dev
    - autoconf
    - libc6-dev
    - libreadline6-dev
    - zlib1g-dev
    - libtool
    - libsqlite3-dev
    - libcurl3
    - libmagickcore-dev
    - ruby-build
#    - ruby-dev
    - libmagickwand-dev
    - imagemagick
#    - bundler
    - redis-server
    - acl
    - debianutils
    - nginx
  register: deps
#- debug: var=deps

- name: apt | Check if packages need to be autoremoved
  command: apt-get --dry-run autoremove
  register: check_autoremove
  changed_when: False
#- debug: var=check_autoremove
- name: apt | Autoremove unused packages
  command: apt-get -y autoremove
#  when: check_autoremove.rc != 0
  when: '"The following packages will be REMOVED:" in check_autoremove.stdout'

- debug: var=ansible_distribution_release
- block:
    - stat: path=/etc/init/sidekiq.conf
      register: sidekiqinit
    ## https://github.com/mperham/sidekiq/wiki/Deployment
    - name: Ubuntu | download upstart script for sidekiq
      get_url:
        url: https://raw.githubusercontent.com/mperham/sidekiq/master/examples/upstart/sidekiq.conf
        dest: /etc/init/sidekiq.conf
        mode: 0644
      when: not sidekiqinit.stat.exists

    - name: Ubuntu | review configuration of upstart script for sidekiq
      replace: dest=/etc/init/sidekiq.conf regexp="{{ item.re }}" replace="{{ item.rep }}"
      with_items:
        - { re: '^# setuid deploy', rep: 'setuid {{ scumblr_rails_user }}' }
        - { re: '^# env HOME=/home/deploy', rep: 'env HOME={{ scumblr_root }}' }
        - { re: '^  # source /home/apps/.bash_profile', rep: '  source /home/{{ scumblr_rails_user }}/.bashrc' }
        - { re: 'cd /var/www/app', rep: 'cd {{ scumblr_root }}' }
      notify:
        - restart rails sidekiq
        - restart rails server
        - restart sidekiq - systemd
        - restart rails/scumblr - systemd
  when: ansible_distribution_release == 'trusty'

