---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Debian | scumblr
  include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Redhat | scumblr
  include: redhat.yml
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Ensure daemons are running and enabled on boot.
  service: name={{ item }} state=started enabled=yes
  with_items:
    - nginx
    - "{{ supervisor_svc }}"
    - "{{ redis_svc }}"

## switch to role https://galaxy.ansible.com/detail#/role/102
#- name: git clone rbenv
#  git: repo=git://github.com/sstephenson/rbenv.git
#       dest=/home/{{ scumblr_rails_user }}/.rbenv
#       accept_hostkey=true
#
#- name: git clone ruby-build
#  git: repo=git://github.com/sstephenson/ruby-build.git
#       dest=/home/{{ scumblr_rails_user }}/.rbenv/plugins/ruby-build
#       accept_hostkey=true
#

- name: create scumblr user
  user: name="{{ scumblr_rails_user }}" home="{{ scumblr_rails_user_home }}" comment="Scumblr rails app user" shell=/bin/bash

- name: ensure right owner for .rbenv
  file: "dest={{ scumblr_rails_user_home }}/.rbenv owner={{ scumblr_rails_user }} recurse=yes state=directory"

- name: enforce no-document for gem
  lineinfile:
    dest: "{{ scumblr_rails_user_home }}/.gemrc"
    line: "gem: --no-document --no-rdoc --no-ri"
    owner: "{{ scumblr_rails_user }}"
    mode: '0600'
    create: yes

- name: update bashrc with appropriate rails env
  lineinfile: 'dest={{ scumblr_rails_user_home }}/.bashrc line="{{ item }}"'
#  lineinfile: 'dest={{ scumblr_rails_user_home }}/.bashrc line=\\"{{ item }}\\"'
#  lineinfile: 'dest={{ scumblr_rails_user_home }}/.bashrc line=\"{{ item }}\"'
  with_items:
    - 'export PATH="$HOME/.rbenv/bin:$PATH"'
    - 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"'
#    - 'eval \"$(rbenv init -)\"'
    - 'eval "$(rbenv init -)"'
## to ensure default actions are on production server else change on cli
    - 'export RAILS_ENV={{ scumblr_rails_env }}'

#- name: install bundler
#  gem: name=bundler state=present
#  become: yes
#  become_user: "{{ scumblr_rails_user }}"
#- name: install rails {{ rails_version }}
#  gem: name=rails version={{ rails_version }} state=present
#  become: yes
#  become_user: "{{ scumblr_rails_user }}"

- file: dest="{{ scumblr_root }}" mode=0755 state=directory owner="{{ scumblr_rails_user }}"

## FIXME! not executing inside rbenv
#- gem: name="{{ item }}" state=present user_install=yes
## FIXME! not idempotent... quick stat to avoid repetition but far from perfect
- name: check which gem is used
  command: "bash -lc \"which {{ item }}\""
  with_items:
    - gem
    - rbenv
  changed_when: false
  register: which
  become: yes
  become_user: "{{ scumblr_rails_user }}"
- debug: var=which
- fail: msg="FATAL! Not right gem binary! where is rbenv gem?"
  when: which is defined and which.results[0].stdout != "{{ scumblr_rails_user_home }}/.rbenv/shims/gem"
- stat: path="{{ scumblr_rails_user_home }}/.rbenv/shims/sidekiq"
  register: gemdep
- name: install gem dependencies inside rbenv
  command: "bash -lc \"gem install {{ item.p }} -v {{ item.v }}\""
  args:
    chdir: "{{ scumblr_root }}"
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  become_flags: "-Hi"
  become_method: sudo
  with_items: "{{ scumblr_gems }}"
  when: not gemdep.stat.exists

## ignore_errors as if repeating, get: msg: Local modifications exist in repository (force=no).
- debug: var=scumblr_version
- name: git clone scumblr
  git: repo=https://github.com/Netflix/Scumblr.git
       dest="{{ scumblr_root }}"
       version="{{ scumblr_version }}"
  ignore_errors: true
  become: yes
  become_user: "{{ scumblr_rails_user }}"

- name: Ensure log directory exists
  file: dest="{{ scumblr_root }}/log" state=directory mode=0755 owner="{{ scumblr_rails_user }}"
- stat: path="{{ scumblr_root }}/log/production.log"
  register: slog
- file: dest="{{ scumblr_root }}/log/production.log" state=touch mode=0666 owner="{{ scumblr_rails_user }}"
  when: not slog.stat.exists
- name: Ensure pids directory exists
  file: dest="{{ scumblr_root }}/tmp/pids" state=directory mode=0755 owner="{{ scumblr_rails_user }}"
#- acl: name="{{ scumblr_root }}/db" entity="{{ www_user }}" etype=user permissions="rwx" state=present
- name: Ensure right permissions on db schema
  acl: name="{{ scumblr_root }}/db/schema.rb" entity="{{ www_user }}" etype=user permissions="rw-" state=present
## v2
#- acl: name="{{ scumblr_root }}/db" entity="{{ www_user }}" etype=user permissions="rwx" state=present recursive=yes

- debug: var=scumblr_db_adapter
- name: configure database backend
  template: "src=database.yml.j2 dest={{ scumblr_root }}/config/database.yml backup=yes"

## not idempotent = use gem 'rbenv-rehash'
#- name: rbenv rehash
#  command: "bash -lc \"rbenv rehash\" chdir={{ scumblr_root }}"
#  become: yes
#  become_user: "{{ scumblr_rails_user }}"

## FIXME! travis/trusty: FAILED! => {"changed": true, "cmd": ["bash", "-lc", "bundle install"], "delta": "0:00:00.225054", "end": "2016-10-30 20:24:08.031412", "failed": true, "invocation": {"module_args": {"_raw_params": "bash -lc \"bundle install\"", "_uses_shell": false, "chdir": "/var/Scumblr", "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 1, "start": "2016-10-30 20:24:07.806358", "stderr": "/home/_scumblr/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (>= 0.a) among 6 total gem(s) (Gem::LoadError)\nChecked in 'GEM_PATH=/home/travis/.rvm/gems/ruby-2.3.1:/home/travis/.rvm/gems/ruby-2.3.1@global:/home/_scumblr/.rbenv/plugins/rbenv-rehash', execute `gem env` for more information\n\tfrom /home/_scumblr/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'\n\tfrom /home/_scumblr/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'\n\tfrom /home/_scumblr/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'", "stdout": "", "stdout_lines": [], "warnings": []}
- name: debug
  command: "{{ item }}"
  with_items:
#    - "bash -lc \"bundle install\" chdir={{ scumblr_root }}"
#    - "bash -lc \"bundle check\" chdir={{ scumblr_root }}"
    - "bash -lc \"gem list\" chdir={{ scumblr_root }}"
    - "bash -lc \"gem env\" chdir={{ scumblr_root }}"
  register: d
  changed_when: false
  become: yes
  become_user: "{{ scumblr_rails_user }}"
- debug: var=d
## bundler v2 OR https://github.com/drewda/ansible-rails
## FIXME! vagrant stalled on this task
## Note: kitchen works with both command, travis only with bash -lc...
- stat: path={{ scumblr_root }}/.ansible_scumblrbundle
  register: touchbundle
- name: bundle install of scumblr
  command: "bash -lc \"bundle install\" chdir={{ scumblr_root }}"
#  bundler: "state=present chdir={{ scumblr_root }} executable={{ scumblr_rails_user_home }}/.rbenv/shims/bundle"
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  when: not touchbundle.stat.exists
- file: dest={{ scumblr_root }}/.ansible_scumblrbundle state=touch
  when: not touchbundle.stat.exists

- stat: path="{{ scumblr_root }}/db/{{ scumblr_rails_env }}.sqlite3"
  register: railsdb
- stat: path={{ scumblr_root }}/.ansible_dbcreate
  register: touchdbcreate
## travis only (kitchen OK): FAILED! => {"changed": true, "cmd": ["bash", "-lc", "rake db:create"], "delta": "0:00:02.775480", "end": "2016-04-07 11:39:09.555950", "failed": true, "invocation": {"module_args": {"_raw_params": "bash -lc \"rake db:create\"", "_uses_shell": false, "chdir": "/var/Scumblr", "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 1, "start": "2016-04-07 11:39:06.780470", "stderr": "rake aborted!\nGem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 10.3.2. Prepending `bundle exec` to your command may solve this.\n/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:34:in `block in setup'\n/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/runtime.rb:19:in `setup'\n/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'\n/usr/local/rvm/gems/ruby-2.2.3/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'\n/var/Scumblr/config/boot.rb:21:in `<top (required)>'\n/var/Scumblr/config/application.rb:16:in `<top (required)>'\n/var/Scumblr/Rakefile:5:in `<top (required)>'\n(See full trace by running task with --trace)", "stdout": "", "stdout_lines": [], "warnings": []}
- name: rake db:create
#  command: "bash -lc \"rake db:create\" chdir={{ scumblr_root }}"
  command: "bash -lc \"bundle exec rake db:create\" chdir={{ scumblr_root }}"
  environment:
    RAILS_ENV: '{{ scumblr_rails_env }}'
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  register: dbcreate
  when: (not railsdb.stat.exists or scumblr_db_adapter != 'sqlite3') and not touchdbcreate.stat.exists
#- debug: var=dbcreate
- file: dest={{ scumblr_root }}/.ansible_dbcreate state=touch
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  when: not touchdbcreate.stat.exists

## FIXME! done at each execution even if schema already loaded
- stat: path={{ scumblr_root }}/.ansible_dbschemaload
  register: touchdbschemaload
- block:
    - name: rake db:schema:load
      command: "bash -lc \"bundle exec rake db:schema:load\" chdir={{ scumblr_root }}"
      environment:
        RAILS_ENV: '{{ scumblr_rails_env }}'
      become: yes
      become_user: "{{ scumblr_rails_user }}"
      register: dbschemaload
  when: not touchdbschemaload.stat.exists and scumblr_version == 'v1.1'
- block:
    - name: rake db:structure:load
      command: "bash -lc \"bundle exec rake db:structure:load\" chdir={{ scumblr_root }}"
      environment:
        RAILS_ENV: '{{ scumblr_rails_env }}'
      become: yes
      become_user: "{{ scumblr_rails_user }}"
      register: dbschemaload
  when: not touchdbschemaload.stat.exists and scumblr_version == 'v2.0'
- debug: var=dbschemaload
  when: not touchdbschemaload.stat.exists
- file: dest={{ scumblr_root }}/.ansible_dbschemaload state=touch
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  when: not touchdbschemaload.stat.exists

- name: generate a rake secret 1
  command: "bash -lc \"bundle exec rake secret\" chdir={{ scumblr_root }}"
  environment:
    RAILS_ENV: '{{ scumblr_rails_env }}'
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  register: rakesecret
  changed_when: False

- name: update config with new secret 1
#  replace: dest="{{ scumblr_root }}/config/initializers/secret_token.rb" regexp="^Scumblr::Application.config.secret_token = '.*$" replace="Scumblr::Application.config.secret_token = '{{ rakesecret.stdout }}'" backup=yes
  replace: dest="{{ scumblr_root }}/config/initializers/secret_token.rb" regexp="^Scumblr::Application.config.secret_token = '4a10f07f41dd720c9e37e1e7677b30f3857a5f5157f7eae517d6ee5aea00c0e794649114c3b2604aacc4a1125c835f7d01977c19e0d1bcce83bbecd87e9a045c'$" replace="Scumblr::Application.config.secret_token = '{{ rakesecret.stdout }}'" backup=yes
  notify:
    - restart rails sidekiq
    - restart rails server
    - restart sidekiq - systemd
    - restart rails/scumblr - systemd
  no_log: True

- name: generate a rake secret 2
  command: "bash -lc \"bundle exec rake secret\" chdir={{ scumblr_root }}"
  environment:
    RAILS_ENV: '{{ scumblr_rails_env }}'
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  register: rakesecret2
  changed_when: False

- name: update config with new secret 2
  replace: dest="{{ scumblr_root }}/config/initializers/devise.rb" regexp={{ item.re }} replace={{ item.rep }} backup=yes
  with_items:
    - { re: "^  config.secret_key = '<DEVISE SECRET KEY>'", rep: "  config.secret_key = '{{ rakesecret2.stdout }}'" }
  notify:
    - restart rails sidekiq
    - restart rails server
    - restart sidekiq - systemd
    - restart rails/scumblr - systemd
  no_log: True
- name: add config to devise.rb
  lineinfile: dest="{{ scumblr_root }}/config/initializers/devise.rb" line={{ item.l }} insertafter={{ item.i }}
  with_items: "{{ scumblr_devise_config }}"
  notify:
    - restart rails sidekiq
    - restart rails server
    - restart sidekiq - systemd
    - restart rails/scumblr - systemd

- stat: path="{{ scumblr_root }}/config/initializers/scumblr.rb"
  register: conf
- name: create services API key config
  command: "rsync -ci {{ scumblr_root }}/config/initializers/scumblr.rb.sample {{ scumblr_root }}/config/initializers/scumblr.rb"
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  register: rsync_result
  changed_when: 'rsync_result.stdout != ""'
  when: not conf.stat.exists
  notify:
    - restart rails sidekiq
    - restart rails server
    - restart sidekiq - systemd
    - restart rails/scumblr - systemd

- include: scumblr-config-v1.yml
  when: scumblr_version == 'v1.1'
- include: scumblr-config-v2.yml
  when: scumblr_version == 'v2.0'

- name: check existing rails users
  command: "bash -lc \"echo \\\"User.all\\\" | rails console\" chdir={{ scumblr_root }}"
  environment:
    RAILS_ENV: '{{ scumblr_rails_env }}'
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  register: userall
  changed_when: false
## FIXME! this doesn't fail when user already exists and is always in changed state or when insertion failed...
- name: add rails user
  include: "scumblr-add-user.yml user={{ item.user }} pass={{ item.pass }} adminstatus={{ item.admin }}"
  with_items: "{{ scumblr_web_users }}"

- name: ensure redis is bind to localhost
  lineinfile: dest={{ redis_conf }} line='bind 127.0.0.1'
  notify:
    - restart redis

## Re run scumblr search every 2 hours?
- name: define cron task to sync every 2 hours
  cron: name="rake sync_all" minute=0 hour="*/2"
        user="{{ scumblr_rails_user }}" job="cd {{ scumblr_root }} && rake sync_all"
        cron_file=ansible_yum-autoupdate
  when: scumblr_cron_rakesync is defined and scumblr_cron_rakesync

- name: configure systemd for sidekiq and rails service
  template: "src=systemd-{{ item }} dest=/lib/systemd/system/{{ item | basename | regex_replace('.j2$', '') }} backup=yes"
  with_items:
    - sidekiq.service.j2
    - scumblr.service.j2
  when: ansible_system == "Linux" and ansible_service_mgr == 'systemd'

- name: configure nginx for scumblr
  template: src=nginx-scumblr.conf.j2 dest="{{ nginx_confdir }}/scumblr.conf" mode=0644
  notify:
    - restart nginx
- name: enable scumblr nginx
  file: "src={{ nginx_confdir }}/scumblr.conf dest=/etc/nginx/sites-enabled/scumblr.conf state=link"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  notify:
    - restart nginx

- block:
    - name: ensure extra providers path exists
      file: dest={{ scumblr_extra_path }} state=directory mode=0755
    - name: install extra providers gem dependencies inside rbenv
      command: "bash -lc \"gem install {{ item.n }} -v {{ item.v }}\" chdir={{ scumblr_root }} creates={{ scumblr_rails_user_home }}/.rbenv/versions/{{ rbenv.ruby_version }}/lib/ruby/gems/{{ rbenv.ruby_version | regex_replace('-[p0-9]*', '') | regex_replace('gems/2.3.1', 'gems/2.3.0') }}/gems/{{ item.n }}-{{ item.v }}"
      with_items: "{{ scumblr_extra_gems }}"
      become: yes
      become_user: "{{ scumblr_rails_user }}"
    - name: adding extra providers (git)
      git: "repo={{ item.u }} dest={{ scumblr_extra_path }}/{{ item.u | basename | regex_replace('.git$', '') }}"
      with_items: "{{ scumblr_extra_providers }}"
#    - name: enable extra provider in main scumblr install
#      file: "src={{ scumblr_extra_path }}/{{ item.0.u | basename }}/{{ item.1 }} dest={{ scumblr_root }}/lib/search_providers state=link"
#      with_subelements:
#        - "{{ scumblr_extra_providers }}"
#        - list
## FIXME! '/var/sketchy/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- shodan (LoadError)'
##      but ```$ echo 'require shodan' | ruby``` works
#      file: "src={{ scumblr_extra_path }}/ScumblrProviders/shodan.rb dest={{ scumblr_root }}/lib/search_providers/shodan.rb state=link"
    - file: "src={{ scumblr_extra_path }}/ScumblrProviders/censys.rb dest={{ scumblr_root }}/lib/search_providers/censys.rb state=link"
    - block:
        - name: set services API key config - extra
          lineinfile: "dest='{{ scumblr_root }}/config/initializers/scumblr.rb' line='  {{ item }}' insertafter='config.twitter_access_token_secret'"
          with_items: "{{ scumblr_extra_config }}"
          notify:
            - restart rails sidekiq
            - restart rails server
            - restart sidekiq - systemd
            - restart rails/scumblr - systemd
          no_log: True
      when: scumblr_extra_config is defined and scumblr_extra_config != []
    - block:
        - name: adding extra providers (get_url)
          get_url: "url={{ item }} dest={{ scumblr_extra_path }}/{{ item | basename }} mode=0644"
          with_items: "{{ scumblr_extra_providers_raw }}"
      when: scumblr_extra_providers_raw is defined and scumblr_extra_providers_raw != []
  when: scumblr_extra_providers is defined and scumblr_extra_providers != []

- file: path={{ scriptsdir }} state=directory mode=0755
- name: add backup script
  template: src=backup-scumblr.sh.j2 dest={{ scriptsdir }}/backup-scumblr.sh mode=0755
- name: add restore script
  template: src=restore-scumblr.sh.j2 dest={{ scriptsdir }}/restore-scumblr.sh mode=0755
- name: setup cron backup
  cron: name="scumblr-backup" minute="30" hour="3" weekday="0"
    job="{{ scriptsdir }}/backup-scumblr.sh > /dev/null 2>&1"
    user=root
    cron_file=ansible_scumblr-backup

- include: restore.yml
  when: (scumblr_db_adapter is defined and scumblr_db_adapter == 'postgresql') and scumblr_db_restorefile is defined and scumblr_db_restorefile != ''

- name: ensure systemd services for sidekiq and rails/scumblr are enabled and started
  service: name={{ item }} state=started enabled=yes
  with_items:
    - sidekiq
    - scumblr
  when: ansible_system == "Linux" and ansible_service_mgr == 'systemd'

- meta: flush_handlers
- name: ensure service is up before ending
## does not support http request
#  wait_for: host=127.0.0.1 port=3000 timeout=30 search_regex='<body>You are being'
  shell: "curl -D - --silent --max-time 5 http://localhost:3000"
  register: result
  until: (result.stdout.find("302 Found") != -1) and (result.stdout.find("<body>You are being") != -1)
  retries: 10
  delay: 3
  changed_when: false
  ignore_errors: true


