---

- name: Redhat | Scumblr dependencies packages install
  yum:
    name:
      - git
      - libxml2-devel
      - bison
      - openssl
      - zlib
      - libxslt-devel
      - openssl-devel
      - libffi-devel
      - libpqxx-devel
      - autoconf
      - glibc-devel
      - readline-devel
      - zlib-devel
      - libtool
      - sqlite-devel
      - libcurl
#      - libmagickcore-dev
      - ruby-devel
#      - libmagickwand-dev
      - python-wand
      - ImageMagick-devel
      - acl
      - crontabs
      - which
      - nginx
    state: present
    update_cache: yes

- stat: path=/usr/lib/systemd/system/sidekiq.conf
  register: sidekiqinit
- name: download upstart script for sidekiq
  get_url:
    url: https://raw.githubusercontent.com/mperham/sidekiq/master/examples/systemd/sidekiq.service
    dest: /usr/lib/systemd/system/sidekiq.conf
    mode: 0644
  when: not sidekiqinit.stat.exists

- name: review configuration of upstart script for sidekiq
  replace:
    dest: /usr/lib/systemd/system/sidekiq.conf
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
  with_items:
    - { re: '^User=deploy', rep: 'User={{ scumblr_rails_user }}' }
    - { re: '^WorkingDirectory=/opt/myapp/current', rep: 'WorkingDirectory={{ scumblr_root }}' }
  notify:
    - restart rails sidekiq
    - restart rails server
    - restart sidekiq - systemd
    - restart rails/scumblr - systemd

# https://github.com/ansible/ansible/issues/16612
- block:
    - debug: var=ansible_selinux
    - name: RedHat | Ensure selinux dependencies are present
      package:
        name: libselinux-python
        state: present
    - action: setup
    - debug: var=ansible_selinux
  when: ansible_os_family == "RedHat"
- block:
    - name: RedHat | Ensure selinux dependencies are present
      package:
        name:
          - libselinux-python
          - libsemanage-python
          - policycoreutils-python
        state: present

    - name: RedHat | Allow proxy to network connect in selinux
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Managing_Confined_Services/sect-Managing_Confined_Services-Configuration_examples-Changing_port_numbers.html
# https://wiki.centos.org/HowTos/SELinux#head-ad837f60830442ae77a81aedd10c20305a811388
    - name: RedHat | Allow httpd to listen to unusual ports
      seport:
        ports: "{{ scumblr_nginx_listen }}"
        proto: tcp
        setype: http_port_t
        state: present
      when: scumblr_nginx_listen != 80 and scumblr_nginx_listen != 443
  when: ansible_os_family == "RedHat" and ansible_selinux.status is defined and ansible_selinux.status != 'disabled'
