---

- name: restart rails sidekiq
#  service: name=sidekiq state=restarted
  command: "bash -lc \"[ X`cat tmp/pids/sidekiq.pid 2>/dev/null` != X ] && kill `cat tmp/pids/sidekiq.pid 2>/dev/null` && sleep 5; bundle exec sidekiq -P tmp/pids/sidekiq.pid -l {{ scumblr_root }}/log/sidekiq.log -d\" chdir={{ scumblr_root }}"
  environment:
    RAILS_ENV: '{{ scumblr_rails_env }}'
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  when: ansible_service_mgr is not defined or ansible_service_mgr != 'systemd'

- name: restart rails server
#  service: name=scumblr state=restarted
  command: "bash -lc \"[ X`cat tmp/pids/server.pid 2>/dev/null` != X ] && kill `cat tmp/pids/server.pid 2>/dev/null` && sleep 5; bundle exec rails s -d > /tmp/rails-s.log 2>&1\" chdir={{ scumblr_root }}"
  environment:
    RAILS_ENV: '{{ scumblr_rails_env }}'
  become: yes
  become_user: "{{ scumblr_rails_user }}"
  when: ansible_service_mgr is not defined or ansible_service_mgr != 'systemd'

- name: restart sidekiq - systemd
  service: name=sidekiq state=restarted
  when: ansible_system == "Linux" and ansible_service_mgr == 'systemd'

- name: restart rails/scumblr - systemd
  service: name=scumblr state=restarted
  when: ansible_system == "Linux" and ansible_service_mgr == 'systemd'

- name: restart redis
  service: name={{ redis_svc }} state=restarted

- name: restart postgres
  service: name=postgresql state=restarted

- name: restart nginx
  service: name=nginx state=restarted

